server/apps/complaints/urls.py
from django.urls import path

from server.apps.complaints.logic.complaint_management import ComplaintCreateView

app_name = 'complaints'

urlpatterns = [
    path('<slug:object_label>/<uuid:object_uuid>/create/', ComplaintCreateView.as_view(), name='complaint-create'),
]

server/apps/drafts/urls.py
from django.urls import path

from server.apps.drafts.logic.drafts import (
    TheoristDraftsBaseTemplateView,
    TheoristDraftsAlbumListView,
    TheoristDraftsTableListView,
    HXTheoristDraftsSearchView,
)
from server.apps.drafts.logic.drafts_management import (
    TheoristDraftCreateView,
    TheoristDraftDeleteView,
    TheoristDraftUpdateView,
)

app_name = 'drafts'

urlpatterns = [
    path('drafts/', TheoristDraftsBaseTemplateView.as_view(), name='base-drafts'),
    path('drafts/album/<uuid:uuid>/', TheoristDraftsAlbumListView.as_view(), name='drafts-album-list'),
    path('drafts/table/<uuid:uuid>/', TheoristDraftsTableListView.as_view(), name='drafts-table-list'),
    path('hx/drafts/search/', HXTheoristDraftsSearchView.as_view(), name='drafts-search'),
    path('drafts/create/', TheoristDraftCreateView.as_view(), name='drafts-create'),
    path('drafts/update/<uuid:uuid>/', TheoristDraftUpdateView.as_view(), name='drafts-edit'),
    path('drafts/delete/<uuid:uuid>/', TheoristDraftDeleteView.as_view(), name='drafts-delete'),
]

server/apps/theorist_drafts/urls.py
from django.urls import path

from server.apps.theorist_drafts.logic.drafts import (
    TheoristDraftsBaseTemplateView,
    TheoristDraftsAlbumListView,
    TheoristDraftsTableListView,
    HXTheoristDraftsSearchView,
)
from server.apps.theorist_drafts.logic.drafts_management import (
    TheoristDraftCreateView,
    TheoristDraftDeleteView,
    TheoristDraftUpdateView,
    TheoristDraftUploadView,
)

app_name = 'drafts'

urlpatterns = [
    path('drafts/', TheoristDraftsBaseTemplateView.as_view(), name='base-drafts'),
    path(
        'drafts/album/<uuid:drafts_configuration_uuid>/',
        TheoristDraftsAlbumListView.as_view(),
        name='drafts-album-list',
    ),
    path(
        'drafts/table/<uuid:drafts_configuration_uuid>/',
        TheoristDraftsTableListView.as_view(),
        name='drafts-table-list',
    ),
    path('hx/drafts/search/', HXTheoristDraftsSearchView.as_view(), name='drafts-search'),
    path('drafts/create/', TheoristDraftCreateView.as_view(), name='drafts-create'),
    path('drafts/update/<uuid:uuid>/', TheoristDraftUpdateView.as_view(), name='drafts-edit'),
    path('drafts/upload/', TheoristDraftUploadView.as_view(), name='drafts-upload'),
    path('drafts/delete/<uuid:uuid>/', TheoristDraftDeleteView.as_view(), name='drafts-delete'),
]

server/urls/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('server.urls.third_party_urls')),
    path(
        '',
        RedirectView.as_view(pattern_name='mathlab:math_news:base-math-news'),
        name='base-redirect',
    ),
    # nested apps urls
    path('mathlab/', include('server.urls.mathlab_urls')),  # this is the main app for math operations
    path('forum/', include('server.urls.forum_urls')),  # math forum
    path('theorist/onboarding/', include('server.apps.theorist.urls.onboarding_urls')),  # theorist onboarding urls
    path('', include('server.apps.users.urls')),  # for auth purposes
    path('exception/', include('server.urls.exception_urls')),  # convenient way to get exception in ajax
    path('complaints/', include('server.apps.complaints.urls')),  # complaints for the objects in the whole project
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/apps/theorist_drafts/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django_lifecycle import LifecycleModel, hook, AFTER_CREATE
from dynamic_filenames import FilePattern

from server.apps.theorist_drafts.querysets import TheoristDraftsConfigurationQuerySet
from server.common.mixins.models import UUIDModelMixin, TimeStampedModelMixin
from server.common.utils.helpers import ConvenientImage

upload_to_pattern_draft = FilePattern(
    filename_pattern='{app_label:.25}/{instance.theorist.full_name_slug}/drafts/{uuid:s}{ext}'
)


class TheoristDrafts(UUIDModelMixin, TimeStampedModelMixin, LifecycleModel):
    draft = models.ImageField(max_length=300, upload_to=upload_to_pattern_draft)

    theorist = models.ForeignKey('theorist.Theorist', on_delete=models.CASCADE, related_name='drafts')

    label = models.CharField(max_length=95, null=True, blank=True)
    description = models.TextField(null=True, blank=True, max_length=255)

    is_public_available = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)
        verbose_name_plural = 'Theorist Drafts'
        verbose_name = 'Theorist Draft'

    def __str__(self):
        return f'{self.label} | {self.__class__.__name__} | id - {self.id}'

    def get_absolute_url(self):
        return reverse('mathlab:drafts:base-drafts')

    def get_draft(self, size: list = None):
        return ConvenientImage(img_field=self.draft, size=size, with_orig_attrs=False)

    @hook(AFTER_CREATE)
    def after_create(self):
        if not self.label:
            self.set_default_label()

    def set_default_label(self):
        drafts_count = TheoristDrafts.objects.filter(theorist=self.theorist).count()
        self.label = _('Draft #%s') % drafts_count
        self.save(update_fields=['label'])


class TheoristDraftsConfiguration(UUIDModelMixin, TimeStampedModelMixin, LifecycleModel):
    theorist = models.OneToOneField('theorist.Theorist', on_delete=models.CASCADE, related_name='drafts_configuration')
    is_public_available = models.BooleanField(default=True)

    objects = TheoristDraftsConfigurationQuerySet.as_manager()

    class Meta:
        ordering = ('-created_at',)
        verbose_name_plural = 'Theorist Drafts Configurations'
        verbose_name = 'Theorist Draft Configuration'

    def __str__(self):
        return f'{self.theorist.full_name} | {self.__class__.__name__} | id - {self.id}'

    def get_share_url(self):
        return reverse('mathlab:drafts:base-drafts') + f'?search_draft={self.uuid}'

server/apps/drafts/forms.py
import base64

from django import forms
from django.core.files.base import ContentFile
from django.utils.translation import gettext_lazy as _

from server.apps.drafts.models import TheoristDrafts


class TheoristDraftCreateForm(forms.ModelForm):
    draft = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = TheoristDrafts
        fields = ('label', 'draft', 'description', 'is_public_available')
        widgets = {
            'label': forms.TextInput(attrs={'placeholder': _('Draft label')}),
            'description': forms.Textarea(attrs={'placeholder': _('Description'), 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        self.theorist = kwargs.pop('theorist')
        super().__init__(*args, **kwargs)
        self.instance.theorist = self.theorist

    def clean_draft(self):
        draft = self.cleaned_data.get('draft')

        # Decode base64 image
        format, imgstr = draft.split(';base64,')
        ext = format.split('/')[-1]
        image_file = ContentFile(base64.b64decode(imgstr), name=f'drawing.{ext}')
        return image_file


class TheoristDraftUpdateForm(forms.ModelForm):
    class Meta:
        model = TheoristDrafts
        fields = ('label', 'description', 'is_public_available')
        widgets = {
            'label': forms.TextInput(attrs={'placeholder': _('Draft label')}),
            'description': forms.Textarea(attrs={'placeholder': _('Description'), 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        self.theorist = kwargs.pop('theorist')
        super().__init__(*args, **kwargs)
        self.instance.theorist = self.theorist

server/apps/theorist_drafts/forms.py
import base64

from django import forms
from django.core.files.base import ContentFile
from django.utils.translation import gettext_lazy as _

from server.apps.theorist_drafts.models import TheoristDrafts


class TheoristDraftCreateForm(forms.ModelForm):
    draft = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = TheoristDrafts
        fields = ('label', 'draft', 'description', 'is_public_available')
        widgets = {
            'label': forms.TextInput(attrs={'placeholder': _('Draft label')}),
            'description': forms.Textarea(attrs={'placeholder': _('Description'), 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        self.theorist = kwargs.pop('theorist')
        super().__init__(*args, **kwargs)
        self.instance.theorist = self.theorist
        self.fields['is_public_available'].initial = True

    def clean_draft(self):
        draft = self.cleaned_data.get('draft')

        # Decode base64 image
        format, imgstr = draft.split(';base64,')
        ext = format.split('/')[-1]
        image_file = ContentFile(base64.b64decode(imgstr), name=f'drawing.{ext}')
        return image_file


class TheoristDraftUpdateForm(forms.ModelForm):
    class Meta:
        model = TheoristDrafts
        fields = ('label', 'description', 'is_public_available')
        widgets = {
            'label': forms.TextInput(attrs={'placeholder': _('Draft label')}),
            'description': forms.Textarea(attrs={'placeholder': _('Description'), 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        self.theorist = kwargs.pop('theorist')
        super().__init__(*args, **kwargs)
        self.instance.theorist = self.theorist


class TheoristDraftUploadForm(forms.ModelForm):
    class Meta:
        model = TheoristDrafts
        fields = ('label', 'description', 'draft', 'is_public_available')
        widgets = {
            'label': forms.TextInput(attrs={'placeholder': _('Draft label')}),
            'description': forms.Textarea(attrs={'placeholder': _('Description'), 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        self.theorist = kwargs.pop('theorist')
        super().__init__(*args, **kwargs)
        self.instance.theorist = self.theorist

server/apps/theorist_drafts/templates/partials/_hs_checkers.html
<script type="text/hyperscript">
  on change from .checker
  if (document.querySelectorAll(".checker:checked").length <= 0 or document.querySelectorAll(".checker:checked").length > 10)
    add .disabled to #share-btn
  else
    remove .disabled from #share-btn
</script>

<script type="text/hyperscript">
  on change from .checker
  if (document.querySelectorAll(".checker:not(:checked)").length > 0)
    set #general-checker.checked to false
  else
    set #general-checker.checked to true
</script>

<script type="text/hyperscript">
  on click from .general-checker
  if (document.querySelectorAll(".checker:checked").length <= 0 or document.querySelectorAll(".checker:checked").length > 10)
    add .disabled to #share-btn
  else
    remove .disabled from #share-btn
</script>

<script type="text/hyperscript">
  on click from #pre-share-btn
  if (document.querySelectorAll(".checker:checked").length <= 0 or document.querySelectorAll(".checker:checked").length > 10)
    add .disabled to #share-btn
  else
    remove .disabled from #share-btn
</script>

server/apps/theorist_drafts/templates/partials/drafts_album_list.html
{% load i18n static %}

<div class="form-check mb-3 d-none general-form-album-checker" style="font-size: 25px;">
  <input type="checkbox"
         id="general-checker"
         _="on click for checkbox in .checker set checkbox.checked to me.checked"
         name="general-check"
         class="form-check-input general-checker mt-2"/>
  <label class="form-check-label" for="general-checker" style="font-size: 22px;">
    {% translate 'Select all' %}
  </label>
</div>

{% if drafts %}
  <div id="album-view-drafts-js">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"
         id="gallery"
         data-toast-trigger
         hx-get="{{ request.get_full_path }}"
         hx-trigger="draftDeleted from:body delay:0.6s"
    >
      {% for draft in drafts %}
        <form id="draftForm-{{ draft.uuid }}" class="col album-draft-base-{{ draft.uuid }}">
          <div class="card shadow-sm">
            <div class="d-none checks d-flex justify-content-center">
              <input style="font-size: 25px;"
                     class="form-check-input checker m-2"
                     type="checkbox"
                     name="draftToShare"
                     value="{{ draft.uuid }}">
            </div>
            <a href="{{ draft.get_draft.url }}"
               data-pswp-width="{{ draft.get_draft.width }}"
               data-pswp-height="{{ draft.get_draft.height }}"
               target="_blank">
              <img class="bd-placeholder-img card-img-top" style="max-width: 430px; max-height: 330px;" src="{{ draft.get_draft.url }}">
            </a>
            <div class="card-body">
              <div class="mb-3 card-text d-flex align-items-center justify-content-between">
                <strong>{{ draft.label }}</strong>
                {% if not draft.is_public_available %}
                  <i class="ti ti-lock text-warning"
                     style="font-size: 23px"
                     data-bs-toggle="tooltip" data-bs-placement="top"
                     title="{% translate 'This draft is not public available.' %}"></i>
                {% endif %}
              </div>
              <p class="card-text">{{ draft.description|default:'' }}</p>
              <div class="d-flex justify-content-between align-items-center flex-md-row flex-column">
                {% if request.theorist == draft.theorist %}
                  <div class="btn-group">
                    <button type="button"
                            hx-get="{% url 'mathlab:drafts:drafts-edit' draft.uuid %}?view={{ request.GET.view }}"
                            hx-target="#drafts-management-modal"
                            hx-trigger="click"
                            data-toast-trigger
                            data-bs-toggle="modal"
                            data-bs-target="#drafts-management-modal"
                            class="btn btn-sm btn-outline-secondary">
                      {% translate 'Edit' %}
                    </button>
                    <button type="button"
                            data-toast-trigger
                            hx-delete="{% url 'mathlab:drafts:drafts-delete' draft.uuid %}?view={{ request.GET.view }}"
                            hx-swap="innerHTML swap:0.5s"
                            hx-target=".album-draft-base-{{ draft.uuid }}"
                            hx-confirm="{% translate 'Are you sure?' %}"
                            class="btn btn-sm btn-outline-danger">
                      {% translate 'Delete' %}
                    </button>
                  </div>
                {% else %}
                  <button class="btn btn-sm btn-outline-danger"
                          hx-get="{% url 'complaints:complaint-create' 'draft' draft.uuid %}"
                          data-toast-trigger
                          hx-target="#complaint-modal"
                          data-bs-target="#complaint-modal"
                          data-bs-toggle="modal"
                          type="button">
                    <i class="ti ti-clipboard-x"></i> {% translate 'Complain' %}
                  </button>
                {% endif %}
                <small class="text-body-secondary small text-muted">{{ draft.created_at }}</small>
              </div>
            </div>
          </div>
        </form>
      {% endfor %}
    </div>
    <div class="mt-5">
      {% include 'common/pagination.html' with htmx_target="#album-view-drafts-js"  %}
    </div>
    {% include 'partials/_hs_checkers.html' %}
  </div>

{% else %}
  {% if theorist %}
    {% if theorist == request.theorist %}
      {% translate 'You can add your first drafts by clicking "Add new draft" button' as msg %}
    {% else %}
      {% translate 'This theorist has no any draft' as msg %}
    {% endif %}
    {% include 'alerts/empty_alert.html' with msg=msg %}
  {% else %}
    {% include 'alerts/not_found_alert.html' %}
  {% endif %}
{% endif %}

server/apps/theorist_drafts/templates/partials/drafts_table.html
{% load i18n static %}
{% load render_table from django_tables2 %}

{% if drafts %}
  <div id="gallery" hx-get="{{ request.get_full_path }}" hx-trigger="draftDeleted from:body">
    {% render_table table %}
  </div>
{% else %}
  {% if theorist %}
    {% if theorist == request.theorist %}
      {% translate 'You can add your first drafts by clicking "Add new draft" button' as msg %}
    {% else %}
      {% translate 'This theorist has no any draft' as msg %}
    {% endif %}
    {% include 'alerts/empty_alert.html' with msg=msg %}
  {% else %}
    {% include 'alerts/not_found_alert.html' %}
  {% endif %}
{% endif %}

{% include 'partials/_hs_checkers.html' %}